#
$(pwd)/ai/opencode:$HOME/.config/opencode
$(pwd)/ai/claude:$HOME/.claude
$(pwd)/ai/agents/skills:$HOME/.claude/skills
$(pwd)/ai/agents:$HOME/.agents
$(pwd)/git:$HOME/.config/git
$(pwd)/tools/act:$HOME/.config/act
$(pwd)/tools/lazydocker:$HOME/.config/lazydocker
$(pwd)/tools/lazygit:$HOME/.config/lazygit
$(pwd)/editor/nvim:$HOME/.config/nvim
$(pwd)/editor/tmux:$HOME/.config/tmux
$(pwd)/editor/tmux/tmuxinator:$HOME/.config/tmuxinator
$(pwd)/editor/tmux/sesh:$HOME/.config/sesh
$(pwd)/zsh/.zshrc:$HOME/.zshrc
$(pwd)/zsh/.zshenv:$HOME/.zshenv
$(pwd)/.npmrc:$HOME/.npmrc
