local M = {}

M.neo_tree = {
  git_status_symbols = {
    -- Change type
    added = "", -- or "✚", but this is redundant info if you use git_status_colors on the name
    modified = "", -- or "", but this is redundant info if you use git_status_colors on the name
    deleted = "", -- this can only be used in the git_status source
    renamed = "➜",
    -- Status type
    unstaged = "✗",
    staged = "✓",
    unmerged = "",
    untracked = "*",
    ignored = "◌",
  },
}

M.navic = {
  File = "󰈙 ",
  Module = " ",
  Namespace = "󰌗 ",
  Package = " ",
  Class = "󰌗 ",
  Method = "󰆧 ",
  Property = " ",
  Field = " ",
  Constructor = " ",
  Enum = "󰕘",
  Interface = "󰕘",
  Function = "󰊕 ",
  Variable = "󰆧 ",
  Constant = "󰏿 ",
  String = "󰀬 ",
  Number = "󰎠 ",
  Boolean = "◩ ",
  Array = "󰅪 ",
  Object = "󰅩 ",
  Key = "󰌋 ",
  Null = "󰟢 ",
  EnumMember = " ",
  Struct = "󰌗 ",
  Event = " ",
  Operator = "󰆕 ",
  TypeParameter = "󰊄 ",
}

M.cmp = {
  Text = "󰉿",
  Method = "m",
  Function = "󰊕",
  Constructor = "",
  Field = "",
  Variable = "󰆧",
  Class = "󰌗",
  Interface = "",
  Module = "",
  Property = "",
  Unit = "",
  Value = "󰎠",
  Enum = "",
  Keyword = "󰌋",
  Snippet = "",
  Color = "󰏘",
  File = "󰈙",
  Reference = "",
  Folder = "󰉋",
  EnumMember = "",
  Constant = "󰇽",
  Struct = "",
  Event = "",
  Operator = "󰆕",
  TypeParameter = "󰊄",
}

M.dbui = {
  expanded = {
    db = "▼",
    buffers = "▼",
    saved_queries = "▼",
    schemas = "▼",
    schema = "▼",
    tables = "▼",
    table = "▼",
  },
  collapsed = {
    db = "▶",
    buffers = "▶",
    saved_queries = "▶",
    schemas = "▶",
    schema = "▶",
    tables = "▶",
    table = "▶",
  },
  saved_query = "*",
  new_query = "+",
  tables = "~",
  buffers = "»",
  add_connection = "[+]",
  connection_ok = "✓",
  connection_error = "✕",
}

M.diagnostic = { Error = " ", Warn = " ", Hint = "󰠠 ", Info = " " }

M.debug = {
  controls = {
    disconnect = "",
    pause = "",
    play = "",
    run_last = "",
    step_back = "",
    step_into = "",
    step_out = "",
    step_over = "",
    terminate = "",
  },
  dapui = {
    collapsed = "",
    current_frame = "",
    expanded = "",
  },
}

M.borders = {
  inner = {
    all = { " ", "▁", " ", "▏", " ", "▔", " ", "▕" },
    top_bottom = { " ", "▁", " ", " ", " ", "▔", " ", " " },
  },
  outer = {
    -- all = { "🭽", "▔", "🭾", "▕", "🭿", "▁", "🭼", "▏" },
    -- all = { "", "", "", "", "", "", "", "" },
    all = { " ", " ", " ", " ", " ", " ", " ", " " },
  },
  none = { "", "", "", "", "", "", "", "" },
  left_right = { "", "", " ", "", "", "", "", " " },
  empty = { " ", " ", " ", " ", " ", " ", " ", " " },
}

M.ts = { -- Treesitter
  IF = "󰉡",
  ELSE = "󰎟",
  FOR = "",
  WHILE = "󰊳",
  SWITCH = "󰊲",
  FUNC = "󰊕",
  VAR = "󰋙",
}

M.dap = {
  Breakpoint = "ß",
  BreakpointCondition = "󰟃",
  BreakpointRejected = "",
  LogPoint = "",
  Pause = "",
  Play = "",
  RunLast = "↻",
  StepBack = "",
  StepInto = "󰆹",
  StepOut = "󰆸",
  StepOver = "󰆷",
  Stopped = "",
  Terminate = "󰝤",
}

M.cmp = {
  buffer = "󰉿",
  latex_symbols = "",
  luasnip = "󰃐",
  nvim_lsp = "",
  nvim_lua = "",
  orgmode = "",
  path = "",
  spell = "󰓆",
  tmux = "",
  treesitter = "",
  undefined = "",
  -- Add source-specific icons here
  codeium = "",
  Codeium = "",
  copilot = "",
  copilot_alt = "",
  Copilot = "",
  Copilot_alt = "",
  TabNine = "",
  cmp_tabnine = "",
}

M.misc = {
  Add = "+",
  Added = "",
  Campass = "󰀹",
  Code = "",
  Gavel = "",
  Ghost = "󰊠",
  Glass = "󰂖",
  Lego = "",
  LspAvailable = "󱜙",
  ManUp = "",
  Neovim = "",
  NoActiveLsp = "󱚧",
  PyEnv = "󰢩",
  Squirrel = "",
  Tag = "",
  Tree = "",
  Vbar = "│",
  Vim = "",
  Watch = "",
}

M.diagnostics = {
  Error = "",
  Warning = "",
  Information = "",
  Question = "",
  Hint = "󰌵",
  -- Hollow version
  Error_alt = "󰅚",
  Warning_alt = "󰀪",
  Information_alt = "",
  Question_alt = "",
  Hint_alt = "󰌶",
}

M.git = {
  Add = "",
  Branch = "",
  Diff = "",
  Git = "󰊢",
  Ignore = "",
  Mod = "M",
  Mod_alt = "",
  Remove = "",
  Rename = "",
  Repo = "",
  Unmerged = "󰘬",
  Untracked = "U",
  Unstaged = "󰄱",
  Staged = "",
  Conflict = "",
}

M.ui = {
  Accepted = "",
  ArrowClosed = "",
  ArrowOpen = "",
  BigCircle = "",
  BigUnfilledCircle = "",
  BookMark = "󰃃",
  Buffer = "󰓩",
  Bug = "",
  Calendar = "",
  Character = "",
  Check = "󰄳",
  ChevronRight = "",
  Circle = "",
  Close = "󰅖",
  Close_alt = "",
  CloudDownload = "",
  CodeAction = "󰌵",
  Comment = "󰅺",
  Dashboard = "",
  DoubleSeparator = "󰄾",
  Emoji = "󰱫",
  EmptyFolder = "",
  EmptyFolderOpen = "",
  File = "󰈤",
  Fire = "",
  Folder = "",
  FolderOpen = "",
  FolderWithHeart = "󱃪",
  Gear = "",
  History = "󰄉",
  Incoming = "󰏷",
  Indicator = "",
  Keyboard = "",
  Left = "",
  List = "",
  Lock = "󰍁",
  Modified = "✥",
  Modified_alt = "",
  NewFile = "",
  Newspaper = "",
  Note = "󰍨",
  Outgoing = "󰏻",
  Package = "",
  Pencil = "󰏫",
  Perf = "󰅒",
  Play = "",
  Project = "",
  Right = "",
  RootFolderOpened = "",
  Search = "󰍉",
  Separator = "",
  SignIn = "",
  SignOut = "",
  Sort = "",
  Spell = "󰓆",
  Square = "",
  Symlink = "",
  SymlinkFolder = "",
  Tab = "",
  Table = "",
  Telescope = "",
  Window = "",
}

M.kind = {
  Break = "󰙧",
  Call = "󰃷",
  Case = "󰬶",
  Class = "󰠱",
  Color = "󰏘",
  Constant = "󰏿",
  Constructor = "",
  Continue = "󰞘",
  Declaration = "󰙠",
  Delete = "󱟁",
  Enum = "",
  EnumMember = "",
  Event = "",
  Field = "󰇽",
  File = "󰈙",
  Folder = "󰉋",
  Fragment = "",
  Function = "󰊕",
  Implementation = "",
  Interface = "",
  Keyword = "󰌋",
  List = "󰅪",
  Loop = "󰑖",
  Method = "󰆧",
  Module = "",
  Namespace = "󰌗",
  Operator = "󰆕",
  Package = "",
  Property = "󰜢",
  Reference = "",
  Regex = "",
  Snippet = "",
  Statement = "󰅩",
  Struct = "",
  Switch = "",
  Text = "󰉿",
  TypeParameter = "󰅲",
  Undefined = "",
  Unit = "",
  Value = "󰎠",
  Variable = "",
  -- ccls-specific icons
  Macro = "",
  Parameter = "",
  StaticMethod = "",
  Terminal = "",
  TypeAlias = "",
}
M.type = {
  Array = "󰅪",
  Boolean = "",
  Null = "󰟢",
  Number = "",
  Object = "󰅩",
  String = "󰉿",
}
M.documents = {
  Default = "",
  File = "",
  FileFind = "󰈞",
  FileTree = "󰙅",
  Files = "",
  Import = "",
  Symlink = "",
  Word = "",
}

return M
