# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
    { on = [ "m" ], run = "plugin bookmarks save", desc = "Save current position as a bookmark" },
    { on = [ "'" ], run = "plugin bookmarks jump", desc = "Jump to a bookmark" },
    { on = [ "b", "d" ], run = "plugin bookmarks delete", desc = "Delete a bookmark" },
    { on = [ "b", "D" ], run = "plugin bookmarks delete_all", desc = "Delete all bookmarks" },

    # Plugin
    { on = ['c', 'm'], run = "plugin chmod",                    desc = "Chmod on selected files" },
    { on = ["g", "l"], run = "plugin lazygit",                  desc = "Run Lazygit" },
    { on = ["d", "u"], run = "plugin restore",                  desc = "Restore last deleted files/folders" },
    { on = ["d", "U"], run = "plugin restore -- --interactive", desc = "Restore deleted files/folders (Interactive)" },
    { on = "l",        run = "plugin --sync smart-enter",       desc = "Enter the child directory, or open the file" },

    { on = ["<Space>", "j"],        run = [ "toggle", "arrow next" ],  desc = "Toggle the current selection state" },
    { on = ["<Space>", "<Space>"],  run = "plugin motions",            desc = "Relative Motions" },
    { on = "f",                     run = "plugin jump-to-char",       desc = "Jump to char" },
    { on = "F",                     run = "plugin smart-filter",       desc = "Smart filter" },

    { on = ["P", "s"], run = "plugin projects save",        desc = "Save project" },
    { on = ["P", "l"], run = "plugin projects load",        desc = "Load project" },
    { on = ["P", "P"], run = "plugin projects load_last",   desc = "Load last project" },
    { on = ["P", "d"], run = "plugin projects delete",      desc = "Delete project" },
    { on = ["P", "D"], run = "plugin projects delete_all",  desc = "Delete all projects" },

    # Goto
    { on = ["g", "h"], run = "cd ~",                            desc = "Go to the Home directory" },
    { on = ["g", "d"], run = "cd $DOTFILES_PATH",               desc = "Go to the Dotfiles" },
    { on = ["g", "<Space>"], run = "cd --interactive",          desc = "Go to a directory interactively" },

    { on = [ "J" ], run = "seek 2",  desc = "Seek down 2 lines in preview" },
    { on = [ "K" ], run = "seek -2", desc = "Seek up 2 lines in preview" },

    { on = "<F3>", run = "plugin mediainfo -- toggle-metadata", desc = "Toggle media preview metadata" },
    { on = "<F4>", run = "plugin mediainfo -- toggle-preview",  desc = "Toggle media preview image" },

]

