-- { -- Testing Integration
--        "nvim-neotest/neotest",
--        dependencies = {
--            "nvim-neotest/nvim-nio",
--            "nvim-lua/plenary.nvim",
--            "antoinemadec/FixCursorHold.nvim",
--            "nvim-treesitter/nvim-treesitter",
--            "nvim-neotest/neotest-python",
--            "nvim-neotest/neotest-plenary",
--            "nvim-neotest/neotest-go",
--            "rouge8/neotest-rust",
--            "rcasia/neotest-bash",
--            "alfaix/neotest-gtest",
--            "nvim-neotest/neotest-jest",
--            "marilari88/neotest-vitest",
--            "stevanmilic/neotest-scala",
--            "lawrence-laz/neotest-zig",
--        },
--        config = function()
--            local neotest_ns = vim.api.nvim_create_namespace("neotest")
--            vim.diagnostic.config({
--                virtual_text = {
--                    format = function(diagnostic)
--                        local message =
--                            diagnostic.message:gsub("\n", " "):gsub("\t", " "):gsub("%s+", " "):gsub("^%s+", "")
--                        return message
--                    end,
--                },
--            }, neotest_ns)
--            require("neotest").setup({
--                adapters = {
--                    require("neotest-go")({
--                        experimental = {
--                            test_table = true,
--                        },
--                        args = {
--                            "-count=1",
--                            "-timeout=60s",
--                            "-race",
--                            "-v",
--                            "-cover",
--                            "-covermode=count" --[[set to `atomic` if run parallel]],
--                        },
--                        recursive_run = true,
--                    }),
--                    require("neotest-rust")({
--                        args = { "--no-capture" },
--                        dap_adapter = "lldb",
--                    }),
--                    require("neotest-jest")({
--                        jestCommand = "npm test --",
--                        -- jestCommand = require("neotest-jest.jest-util").getJestCommand(vim.fn.expand("%:p:h"))
--                        -- 	.. " --watch",
--                        jestConfigFile = "custom.jest.config.ts",
--                        env = { CI = true },
--                        cwd = function(path)
--                            return vim.fn.getcwd()
--                        end,
--                    }),
--                    require("neotest-vitest")({
--                        filter_dir = function(name, rel_path, root)
--                            return name ~= "node_modules"
--                        end,
--                    }),
--                    require("neotest-scala")({
--                        runner = "sbt",
--                        framework = "scalatest",
--                    }),
--                    require("neotest").setup({
--                        log_level = vim.log.levels.TRACE,
--                    }),
--                    require("neotest-gtest").setup({}),
--                    require("neotest-python")({
--                        dap = { justMyCode = false },
--                    }),
--                    require("neotest-plenary"),
--                    require("neotest-bash"),
--                },
--            })
--        end,
--    }
