unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

set -g base-index 1
set -g mouse on
set -sg escape-time 0

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
#

set -g status-style fg=white,bg=black
set -g window-status-current-style fg=green,bg=black
set -g pane-active-border-style fg=green,bg=black
set -g window-status-format " #I:#W#F "
set -g window-status-current-format " #I:#W#F "
set -g window-status-current-style bg=green,fg=black
set -g window-status-activity-style bg=black,fg=yellow
set -g window-status-separator ""
set -g status-justify centre



bind c new-window -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/.tmux.conf \; display "Config reloaded!"

set -g @plugin 'tmux-plugins/tpm'  # Plugin Manager

run -b '~/.config/.tmux/plugins/tpm/tpm' # keep at the bottom
