local M = {}

M.intelephense = {
  cmd = { "intelephense", "--stdio" },
  filetypes = { "php", "blade" },
  root_markers = { ".git", "composer.json" },
  init_options = {
    storagePath = vim.fn.stdpath "cache" .. "/intelephense",
    licenseKey = os.getenv "INTELEPHENSE_LICENSE_KEY",
  },
  settings = {
    intelephense = {
      diagnostics = { enable = false },
      files = {
        maxSize = 20 * 1024 * 1024,
        associations = { "*.php", "*.phtml" },
        exclude = { "**/vendor/**/vendor/**", "**/.git/**", "**/node_modules/**" },
      },
      completion = {
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = false,
        triggerParameterHints = true,
        maxItems = 100,
      },
      stubs = {
        "apache",
        "bcmath",
        "Core",
        "curl",
        "date",
        "dom",
        "fileinfo",
        "filter",
        "gd",
        "hash",
        "iconv",
        "json",
        "mbstring",
        "mysqli",
        "openssl",
        "pcre",
        "PDO",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Reflection",
        "session",
        "SimpleXML",
        "sodium",
        "SPL",
        "sqlite3",
        "standard",
        "superglobals",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlwriter",
        "Zend OPcache",
        "zip",
        "zlib",
        "Illuminate",
        "Laravel",
      },
    },
  },
}

return M
